### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by jmcnamara** [jmcnamara/polars_excel_writer#1]
Work in progress.

**Comment by jmcnamara** [comment]
Todo

`[ExcelWriter](https://docs.rs/polars_excel_writer/latest/polars_excel_writer/struct.ExcelWriter.html)`: This is mainly done. The interface is meant to be simple/minimal and most of the applicable `CvsWriter` features are already implemented. I will evaluate additional functionality (Table support maybe) and add them on request.

[ExcelWriter](https://docs.rs/polars_excel_writer/latest/polars_excel_writer/struct.ExcelWriter.html). This is a bit behind the  Polars Python [ExcelWriter](https://docs.rs/polars_excel_writer/latest/polars_excel_writer/struct.ExcelWriter.html) interface. Some features that will be added in the short term:

- [ ] Support to Table configuration
- [ ] Option to add more worksheet (and write to them)
- [ ] Option to rename worksheets
- [ ] Option to set column formats
- [ ] Option to convert formula strings into formulas
- [ ] Option to convert url strings into urls
- [ ] Option to add formats based on Polars `dtypes`
- [ ] Others

**Comment by adrivn** [comment]
Hi John! Loving your dedication to these libraries. Any plans/updates for this project?

Thank you

**Comment by jmcnamara** [comment]
@adrivn 

> Any plans/updates for this project?

I plan to work through the roadmap above over the next few months. Probably starting with the `dtype_formats` and `column_formats`.

Which features are you interested in?

**Comment by adrivn** [comment]
> Which features are you interested in?

Those two, along with `formulas` and `header_format`. 

There is another thing: a high-level API interface to either create themes or load themes from Office theme files (`.thmx`). I understand this may be harder to implement or lower priority to the rest, but it would be a nice to have.

Thanks again for your dedication.

**Comment by jmcnamara** [comment]
> There is another thing: a high-level API interface to either create themes or load themes

This one is trickier than it first seems. In theory I could add an interface to allow the user to add a raw theme.xml file from another Excel file. However, changing the theme usually changes the default font, font size, row height and column width. These all have an effect on Excel's positioning calculations for worksheet objects such as images, charts and textboxes. So in order to change theme the user would have to add additional metadata such as font  heights and widths to avoid images getting squashed or stretched. That combined with this being an infrequently requested feature means I haven't implemented it.

What theme(s) would you want to use?

**Comment by adrivn** [comment]
Now that you lay out the details, it might indeed be overkill to implement an API for loading theme .XML files if the usage is infrequent.

Perhaps some high-level cell/range styling API? Again, this is some nice-to-have, thus lower priority.

**Comment by ADR-43** [comment]
Hello, thank you for your contributions and dedication to these packages!! Is there going to be implementation of workbooks in the near future? I am starting to port some old python code to rust and the outputs need to be combined into one. I can implement a basic version myself, but I don't trust it to be optimal as I have other responsibilities. Thank you for your time!

**Comment by jmcnamara** [comment]
> Is there going to be implementation of workbooks in the near future? I am starting to port some old python code to rust and the outputs need to be combined into one.

I'm not sure if it fits your use case (if not please explain it a bit more) but it is possible to use a `rust_xlsxwriter` workbook and just use `polar_excel_writer` to write data to one or more worksheets and add those to the workbook:

```rust

use polars::prelude::*;
use polars_excel_writer::PolarsXlsxWriter;
use rust_xlsxwriter::Workbook;

fn main() -> PolarsResult<()> {
    // Create a sample dataframe using `Polars`
    let df: DataFrame = df!(
        "Data" => &[10, 20, 15, 25, 30, 20],
    )?;

    // Create the xlsx_writer instance.
    let mut xlsx_writer = PolarsXlsxWriter::new();

    // Create a new workbook and worksheet using `rust_xlsxwriter`.
    let mut workbook = Workbook::new();
    let worksheet = workbook.add_worksheet();

    // Write the dataframe to the worksheet using `xlsx_writer`.
    xlsx_writer.write_dataframe_to_worksheet(&df, worksheet, 0, 0)?;

    // Get another worksheet and write data to that too.
    let worksheet = workbook.add_worksheet();
    xlsx_writer.write_dataframe_to_worksheet(&df, worksheet, 0, 0)?;

    // Save the file to disk.
    workbook.save("workbook.xlsx")?;

    Ok(())
}
```

See the following for an explanation:

- [Interacting with rust_xlsxwriter](https://docs.rs/polars_excel_writer/latest/polars_excel_writer/xlsx_writer/struct.PolarsXlsxWriter.html#interacting-with-rust_xlsxwriter)

- [write_dataframe_to_workshee()](https://docs.rs/polars_excel_writer/latest/polars_excel_writer/xlsx_writer/struct.PolarsXlsxWriter.html#method.write_dataframe_to_worksheet)

There is also the `add_worksheet()` method to add a worksheet without getting the workbook:

- [add_worksheet()](https://docs.rs/polars_excel_writer/latest/polars_excel_writer/xlsx_writer/struct.PolarsXlsxWriter.html#method.add_worksheet)

**Comment by ADR-43** [comment]
Ah, my apologies for my ignorance. I was flipping between the documentation of polars, this, and rust_xlsxwriter so much that I got myself turned around and didn't see that. Thank you for taking the time to respond!!

**Comment by jmcnamara** [comment]
Version v0.14.0 of `polars_excel_writer` has been released. This is a significant update with support for setting dataframe formatting based on data types or columns.  It also adds header formatting. See the following function in the updated documentation:

  - `PolarsXlsxWriter::set_dtype_format()`
  - `PolarsXlsxWriter::set_column_format()`
  - `PolarsXlsxWriter::set_header_format()`

The following functions are deprecated in favour of `PolarsXlsxWriter::set_dtype_format()` and variants:

  - `PolarsXlsxWriter::set_float_format()`
  - `PolarsXlsxWriter::set_time_format()`
  - `PolarsXlsxWriter::set_date_format()`
  - `PolarsXlsxWriter::set_datetime_format()`

**Comment by jmcnamara** [comment]
**Update, May 2025**. 

I plan to do a significant amount of work on `polars_excel_writer` over the next few months to close the gap with Polars' `write_excel` functionality. I also plan to significantly upgrade the documentation with more detailed examples and a cookbook.

In order to do this some features/APIs will need to be deprecated and replaced. In particular  the next version of this crate will drop support for the Polars `SerWriter` interface or move it to another crate in order to maximize
compatibility with the Polars `write_excel` interface. If people use the `SerWriter` interface please shout now.

The next version may also break backward compatibility with some APIs or interfaces but this will be minimized as much as possible and is aimed at improving overall consistency and making the code easier to maintain and extend.

**Comment by mlagoma** [comment]
Greetings, and thanks for your work!

Looks like I was late to the discussion, but I did like having the `SerWriter` interface for not requiring writing to a file.

I do see the `rustxlsx_writer` already has a `save_to_buffer`, would it be possible to add that to `PolarsExcelWriter`?

**Comment by jmcnamara** [comment]
@mlagoma 

> I've figured out how to do it by adding `rust_xlsxwriter` and using the `Workbook`

For what it is worth here is an example of doing that in case anyone else needs it:

```rust
use polars::prelude::*;
use polars_excel_writer::PolarsExcelWriter;
use rust_xlsxwriter::Workbook;

fn main() -> PolarsResult<()> {
    // Create a sample dataframe using `Polars`,
    let df: DataFrame = df!(
        "Data" => &[10, 20, 15, 25, 30, 20],
    )?;

    // Create a new workbook and worksheet using `rust_xlsxwriter`.
    let mut workbook = Workbook::new();
    let worksheet = workbook.add_worksheet();

    // Write the dataframe to the worksheet using `PolarsExcelWriter`.
    let mut excel_writer = PolarsExcelWriter::new();
    excel_writer.write_dataframe_to_worksheet(&df, worksheet, 0, 0)?;

    // Save the workbook to a buffer.
    let buf = workbook.save_to_buffer()?;

    println!("File size: {}", buf.len());

    Ok(())
}
```

> I was going to ask if this could be added to `PolarsExcelWriter`, but I can leave that up to you to decide.

Yes, I may add that.

There is an undocumented `save_to_writer()` method that was required for the `SerWriter` implementation. I will probably make that public in future. That could also be use to write to a buffer.


```rust
use std::fs::File;
use std::io::{Cursor, Write};

use polars::prelude::*;
use polars_excel_writer::PolarsExcelWriter;

fn main() -> PolarsResult<()> {
    // Create a sample dataframe using `Polars`,
    let df: DataFrame = df!(
        "Data" => &[10, 20, 15, 25, 30, 20],
    )?;

    // Create a new Excel writer.
    let mut excel_writer = PolarsExcelWriter::new();

    // Save the dataframe to a buffer. It is wrapped in a Cursor because it
    // needs to implement the `Seek` trait.
    let mut cursor = Cursor::new(Vec::new());
    excel_writer.save_to_writer(&df, &mut cursor)?;

    // Write the buffer to a file for the sake of the example.
    let buf = cursor.into_inner();
    let mut file = File::create("dataframe.xlsx")?;
    Write::write_all(&mut file, &buf)?;

    Ok(())
}
```

**Comment by HeWhoHeWho** [comment]
Hi I'm reading through some of your work and came across this thread, at the same time in search of a more performant excel writer.

Just checking, would this project be integrated with Python Polars in near future?

**Comment by jmcnamara** [comment]
> Just checking, would this project be integrated with Python Polars in near future?

@HeWhoHeWho 

In the "near" future probably not but I hope that it will be at some point. To that end I am structuring it so that it could be a drop in replacement for the Python XlsxWriter library that Polars currently uses (and which I also wrote). 

In case you are interested here is a comparison of the two:

https://docs.rs/polars_excel_writer/latest/polars_excel_writer/polars_comparison/index.html
